### ISSUE TITLE
Animations in XAML?

### ISSUE THREAD

**Issue by nikolalukovic** [LanceMcCarthy/MauiSuggestions#1]
Most of my experience with UI in .NET world comes from WPF. And even though it wasn't perfect, i was able to do a considerable amount of animations from XAML there. As far as I know in Xamarin.Forms all animations are done in code. Which is, in my opinion, crude, unwieldy and makes code an unreadable mess. Their place should be in XAML. I didn't create a PR since I don't know if community would even want something like this. So i created this issue to discuss about these things.

**Comment by LanceMcCarthy** [comment]
Indeed, right now they're not directly configurable in XAML because there is no XAML interface.
It is still possible, but you need to first [create a behavior](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/creating) for that animation, write the animation in code for the `bindable`, and then use that behavior to the UI control.

I'll figure out a way to add it to the readme table. Maybe as a new attached property.

**Comment by nikolalukovic** [comment]
Yeah, but the animation work is still done by code if I understand this correctly. What would be amazing is to have something like this: https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-animate-the-size-of-a-frameworkelement with storyboards.

**Comment by LanceMcCarthy** [comment]
Yeah Storyboarding is amazing, it was my go-to in Expression Blend! I have figured out how to add this feedback to the table in a meaningful way to include it with the other XAML suggestions.

I'm only closing this because it's on the readme now, if you have anything else to add, don't hesitate to post again in here because the readme points back to this thread
