### ISSUE TITLE
Editor is not equivalent to RichTextBox

### ISSUE THREAD

**Issue by PerfectlyFineCode** [LanceMcCarthy/MauiSuggestions#8]
As title suggests, Editor is not equivalent to RichTextBox.
Editor does not have the properties that RichTextBox has, such as Document, etc.

**Comment by LanceMcCarthy** [comment]
Hi @PerfectlyFineCode this repo is a bit old, it was before there was an official place to leave feedback for the Microsoft team.

The good news is there is  now a good spot to do this, check out => https://github.com/dotnet/maui and go to https://github.com/dotnet/maui/discussions

To your original point, yes Editor is not a RichTextBox because it doesn't use a document model (i.e. FlowDocument). 

Side Note: Telerik UI for MAUI is expecting to have ported the UI for Xamarin.Forms RichTextBox to MAUI soon https://docs.telerik.com/devtools/xamarin/controls/richtexteditor/richtexteditor-overview
